// Vue - Angular - React/React/react-project/src/components/Faq/Faq.js
import React, {Component} from 'react';
import './Faq.css';
import axios from 'axios'

class Faq extends Component {

    constructor(props) {
        super(props);

        this.state = {
            faqs: []
        };
    }

    componentDidMount() {
        axios.get('https://jsonplaceholder.typicode.com/posts')
            .then(res => {
                    const faqs = res.data.slice(0, 10);
                    this.setState({faqs});
                })
    }

    render() {
        return (
            <div className="faq">
                <div className="container">
                    <section className="section">
                        <h1 className="title">FAQ</h1>
                        <h2 className="subtitle is-4">
                            Duis feugiat, risus quis rhoncus semper, ligula lorem facilisis risus, non varius nunc enim
                            a dui. Donec elit
                            lacus, hendrerit eget tortor quis, efficitur vestibulum lectus. In posuere
                        </h2>

                        <div className="columns">
                            { this.state.faqs.map(faq =>
                                <div className="column is-one-third" v-for="faq of faqs">
                                    <div className="card">
                                        <div className="card-content">
                                            <p className="title">1{ faq.title }</p>
                                            <p className="answer">2{ faq.body }</p>
                                        </div>
                                    </div>
                                </div>
                            )}
                        </div>
                    </section>
                </div>
            </div>
        );
    }
}

export default Faq;

// Vue - Angular - React/Vue/vue-project/src/components/FAQ.vue
<template>
  <div class="faq">
    <div class="container">
      <section class="section">
        <h1 class="title">FAQ</h1>
        <h2 class="subtitle is-4">
          Duis feugiat, risus quis rhoncus semper, ligula lorem facilisis risus, non varius nunc enim a dui. Donec elit
          lacus, hendrerit eget tortor quis, efficitur vestibulum lectus. In posuere
        </h2>

        <div class="columns" v-if="faqs && faqs.length">
          <div class="column is-one-third" v-for="faq of faqs">
            <div class="card">
              <div class="card-content">
                <p class="title">1{{ faq.title }}</p>
                <p class="answer">2{{ faq.body }}</p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</template>

<script>

  import axios from 'axios';

  export default {
    name: 'faq',
    data: () => ({
      faqs: [],
      errors: []
    }),

    created() {
      axios.get('https://jsonplaceholder.typicode.com/posts')
        .then(response => {
          this.faqs = response.data.slice(0, 10);
        })
        .catch(e => {
          this.errors.push(e)
        })
    }
  }
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="sass">
  @import '../mq'

  .pd
    padding: 2.5em 0 1.5em 0

  .answer
    margin-top: 10px !important
    color: gray

  .columns
    flex-wrap: wrap
</style>
