// Vue - Angular - React/React/react-project/src/components/Faq/Faq.js
import React, {Component} from 'react';
import './Faq.css';
import axios from 'axios'

class Faq extends Component {

    constructor(props) {
        super(props);

        this.state = {
            faqs: []
        };
    }

    componentDidMount() {
        axios.get('https://jsonplaceholder.typicode.com/posts')
            .then(res => {
                    const faqs = res.data.slice(0, 10);
                    this.setState({faqs});
                })
    }

    render() {
        return (
            <div className="faq">
                <div className="container">
                    <section className="section">
                        <h1 className="title">FAQ</h1>
                        <h2 className="subtitle is-4">
                            Duis feugiat, risus quis rhoncus semper, ligula lorem facilisis risus, non varius nunc enim
                            a dui. Donec elit
                            lacus, hendrerit eget tortor quis, efficitur vestibulum lectus. In posuere
                        </h2>

                        <div className="columns">
                            { this.state.faqs.map(faq =>
                                <div className="column is-one-third" v-for="faq of faqs">
                                    <div className="card">
                                        <div className="card-content">
                                            <p className="title">1{ faq.title }</p>
                                            <p className="answer">2{ faq.body }</p>
                                        </div>
                                    </div>
                                </div>
                            )}
                        </div>
                    </section>
                </div>
            </div>
        );
    }
}

export default Faq;

// Vue - Angular - React/Angular/angular-project/src/app/faq/faq.component.ts
import { Component, OnInit } from '@angular/core';

import {HttpClient} from '@angular/common/http';

@Component({
  selector: 'app-faq',
  templateUrl: './faq.component.html',
  styleUrls: ['./faq.component.sass']
})
export class FaqComponent implements OnInit {

  faqs: Object;

  constructor(private http: HttpClient) {
    this.http.get('https://jsonplaceholder.typicode.com/posts')
      .subscribe(res => this.faqs = res);
  }

  ngOnInit(): void {
  }

}

<div class="faq">
  <div class="container">
    <section class="section">
      <h1 class="title">FAQ</h1>
      <h2 class="subtitle is-4">
        Duis feugiat, risus quis rhoncus semper, ligula lorem facilisis risus, non varius nunc enim a dui. Donec elit
        lacus, hendrerit eget tortor quis, efficitur vestibulum lectus. In posuere
      </h2>

      <div class="columns">
        <div class="column is-one-third" *ngFor="let faq of (faqs);  let i = index;">
          <div class="card" *ngIf="i < 10">
            <div class="card-content">
              <p class="title">{{faq.title}}</p>
              <p class="answer">{{faq.body}}</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>
