// Vue - Angular - React/Vue/vue-project/src/App.vue
<template>
  <div id="app">
    <div class="navbar">
      <div class="navbar-start">
        <router-link to="/" class="navbar-item">My Company</router-link>
      </div>
      <div class="navbar-end">
        <div class="navbar-burger" v-on:click="toggleNav" v-bind:class="{ 'is-active': isActive }">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </div>

        <div class="navbar-menu" v-bind:class="{ 'is-active': isActive }">
          <router-link to="/" class="navbar-item r-item">Home</router-link>
          <router-link to="faq" class="navbar-item r-item">Features</router-link>
          <router-link to="faq" class="navbar-item r-item">About</router-link>
          <router-link to="faq" class="navbar-item r-item">FAQ</router-link>

          <div class="navbar-item">
            <p class="control">
              <a class="button is-primary is-outlined">
                <span class="icon">
                  <i class="fa fa-download"></i>
                </span>
                <span>Join Now</span>
              </a>
            </p>
          </div>
        </div>

      </div>
    </div>
    <router-view></router-view>

    <footer class="footer is-primary">
      <div class="container">
        <div class="column">
          <p>And this right here is a siffy footer, where you can put stuff</p>
        </div>
        <div class="column has-text-right">
          <a class="icon" href="#"><i class="fab fa-facebook-square"></i></a>
          <a class="icon" href="#"><i class="fab fa-twitter"></i></a>
        </div>
      </div>
    </footer>

  </div>
</template>

<script>
  export default {
    name: 'App',
    data: function() {
      return {
        isActive: false
      }
    },
    methods: {
      toggleNav: function () {
        this.isActive = !this.isActive;
      }
    }
  }


</script>

<style lang="sass">

  @import '../node_modules/bulma/bulma.sass'
  @import 'mq'

  .navbar
    background-color: #383838
    a:hover
      color: gray
      background-color: #383838

  .navbar-start a
    color: white
    font-weight: bold

  a.r-item
    color: #c1c1c1
    padding: 0.5rem 1.75rem
    +mobile
      color: gray
      &:hover
        background-color: rebeccapurple

  .navbar-burger
    background-color: #C1C1C1

  footer
    background-color: $primary !important
    color: white

    .icon
      color: #fff
      margin-left: 20px


</style>

// Vue - Angular - React/Angular/angular-project/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.sass']
})
export class AppComponent {
 // toggleNav: false;
  toggleNav: boolean = false;
}

<div id="app">
  <div class="navbar">
    <div class="navbar navbar-start">
      <a routerLink="/" class="navbar-item">My Company</a>
    </div>
    <div class="navbar-end">
      <div class="navbar-burger" (click)="toggleNav = !toggleNav;" [ngClass]="{'is-active' : toggleNav }">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </div>

      <div class="navbar-menu"  [ngClass]="{'is-active' : toggleNav }">
        <a routerLink="/" class="navbar-item r-item">Home</a>
        <a routerLink="faq" class="navbar-item r-item">Features</a>
        <a routerLink="faq" class="navbar-item r-item">About</a>
        <a routerLink="faq" class="navbar-item r-item">FAQ</a>

        <div class="navbar-item">
          <p class="control">
            <a class="button is-primary is-outlined">
                <span class="icon">
                  <i class="fa fa-download"></i>
                </span>
              <span>Join Now</span>
            </a>
          </p>
        </div>
      </div>
    </div>
  </div>

</div>

<router-outlet></router-outlet>

<footer class="footer is-primary">
  <div class="container">
    <div class="column">
      <p>And this right here is a spiffy footer, where you can put stuff</p>
    </div>
    <div class="column has-text-right">
      <a class="icon" href="#"><i class="fa fa-facebook-square"></i></a>
      <a class="icon" href="#"><i class="fa fa-twitter"></i></a>
    </div>
  </div>
</footer>
